{{if .Values.mappedSecrets}}
{{- $fullName := include "simple-docker-app.fullname" . -}}
{{- if gt (len .Values.mappedSecrets) 0 }}
{{- range $k, $v := .Values.mappedSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-{{ $k }}-external-secret
spec:
  {{- toYaml $v | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
