apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-docker-app.fullname" . }}
  labels:
    {{- include "simple-docker-app.labels" . | nindent 4 }}
  {{- if (and .Values.metrics.enabled .Values.metrics.service.annotations) }}
  annotations:
    {{- if and .Values.metrics.enabled .Values.metrics.service.annotations }}
    {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "simple-docker-app.selectorLabels" . | nindent 4 }}
